import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from '@react-oauth/google';
import { Toaster } from "react-hot-toast";
 import {QueryClientProvider, QueryClient} from '@tanstack/react-query'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
const inter = Inter({ subsets: ["latin"] });

const queryClient=new QueryClient()
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
      <GoogleOAuthProvider clientId="938126689712-2v5vommtm8mbb4rggagh20ss9j2p4tb5.apps.googleusercontent.com">{children}
        <Toaster />
       
      </GoogleOAuthProvider>
   
      </body>
    </html>
  );
}
